// Code generated by MockGen. DO NOT EDIT.
// Source: aci_network.go

// Package network is a generated GoMock package.
package network

import (
    context "context"
    gomock "github.com/golang/mock/gomock"
    reflect "reflect"
    aznetworkv2 "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v2"
    "github.com/virtual-kubelet/azure-aci/pkg/auth"
    azaciv2 "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerinstance/armcontainerinstance/v2"
    v1 "k8s.io/api/core/v1"
)

// MockProviderNetworkInterface is a mock of ProviderNetworkInterface interface.
type MockProviderNetworkInterface struct {
    ctrl     *gomock.Controller
    recorder *MockProviderNetworkInterfaceMockRecorder
}

// MockProviderNetworkInterfaceMockRecorder is the mock recorder for MockProviderNetworkInterface.
type MockProviderNetworkInterfaceMockRecorder struct {
    mock *MockProviderNetworkInterface
}

// NewMockProviderNetworkInterface creates a new mock instance.
func NewMockProviderNetworkInterface(ctrl *gomock.Controller) *MockProviderNetworkInterface {
    mock := &MockProviderNetworkInterface{ctrl: ctrl}
    mock.recorder = &MockProviderNetworkInterfaceMockRecorder{mock}
    return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderNetworkInterface) EXPECT() *MockProviderNetworkInterfaceMockRecorder {
    return m.recorder
}

// SetVNETConfig mocks base method.
func (m *MockProviderNetworkInterface) SetVNETConfig(ctx context.Context, azConfig *auth.Config) error {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "SetVNETConfig", ctx, azConfig)
    ret0, _ := ret[0].(error)
    return ret0
}

// SetVNETConfig indicates an expected call of SetVNETConfig.
func (mr *MockProviderNetworkInterfaceMockRecorder) SetVNETConfig(ctx, azConfig interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVNETConfig", reflect.TypeOf((*MockProviderNetworkInterface)(nil).SetVNETConfig), ctx, azConfig)
}

// GetACISubnet mocks base method.
func (m *MockProviderNetworkInterface) GetACISubnet(ctx context.Context, subnetsClient *aznetworkv2.SubnetsClient) (aznetworkv2.Subnet, error) {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "GetACISubnet", ctx, subnetsClient)
    ret0, _ := ret[0].(aznetworkv2.Subnet)
    ret1, _ := ret[1].(error)
    return ret0, ret1
}

// GetACISubnet indicates an expected call of GetACISubnet.
func (mr *MockProviderNetworkInterfaceMockRecorder) GetACISubnet(ctx, subnetsClient interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetACISubnet", reflect.TypeOf((*MockProviderNetworkInterface)(nil).GetACISubnet), ctx, subnetsClient)
}

// GetSubnetClient mocks base method.
func (m *MockProviderNetworkInterface) GetSubnetClient(ctx context.Context, azConfig *auth.Config) (*aznetworkv2.SubnetsClient, error) {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "GetSubnetClient", ctx, azConfig)
    ret0, _ := ret[0].(*aznetworkv2.SubnetsClient)
    ret1, _ := ret[1].(error)
    return ret0, ret1
}

// GetSubnetClient indicates an expected call of GetSubnetClient.
func (mr *MockProviderNetworkInterfaceMockRecorder) GetSubnetClient(ctx, azConfig interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetClient", reflect.TypeOf((*MockProviderNetworkInterface)(nil).GetSubnetClient), ctx, azConfig)
}

// CreateOrUpdateACISubnet mocks base method.
func (m *MockProviderNetworkInterface) CreateOrUpdateACISubnet(ctx context.Context, subnetsClient *aznetworkv2.SubnetsClient, currentSubnet aznetworkv2.Subnet) error {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "CreateOrUpdateACISubnet", ctx, subnetsClient, currentSubnet)
    ret0, _ := ret[0].(error)
    return ret0
}

// CreateOrUpdateACISubnet indicates an expected call of CreateOrUpdateACISubnet.
func (mr *MockProviderNetworkInterfaceMockRecorder) CreateOrUpdateACISubnet(ctx, subnetsClient, currentSubnet interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateACISubnet", reflect.TypeOf((*MockProviderNetworkInterface)(nil).CreateOrUpdateACISubnet), ctx, subnetsClient, currentSubnet)
}

// AmendVnetResources mocks base method.
func (m *MockProviderNetworkInterface) AmendVnetResources(ctx context.Context, cg azaciv2.ContainerGroup, pod *v1.Pod, clusterDomain string) {
    m.ctrl.T.Helper()
    m.ctrl.Call(m, "AmendVnetResources", ctx, cg, pod, clusterDomain)
}

// AmendVnetResources indicates an expected call of AmendVnetResources.
func (mr *MockProviderNetworkInterfaceMockRecorder) AmendVnetResources(ctx, cg, pod, clusterDomain interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AmendVnetResources", reflect.TypeOf((*MockProviderNetworkInterface)(nil).AmendVnetResources), ctx, cg, pod, clusterDomain)
}