// Code generated by MockGen. DO NOT EDIT.
// Source: subnets_client.go

// Package network is a generated GoMock package.
package network

import (
	aznetworkv2 "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork/v2"
    context "context"
    gomock "github.com/golang/mock/gomock"
    reflect "reflect"
	//runtime "github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// MockSubnetsClientInterface is a mock of SubnetsClientInterface interface.
type MockSubnetsClientInterface struct {
    ctrl     *gomock.Controller
    recorder *MockSubnetsClientInterfaceMockRecorder
}

// MockSubnetsClientInterfaceMockRecorder is the mock recorder for MockSubnetsClientInterface.
type MockSubnetsClientInterfaceMockRecorder struct {
    mock *MockSubnetsClientInterface
}

// NewMockSubnetsClientInterface creates a new mock instance.
func NewMockSubnetsClientInterface(ctrl *gomock.Controller) *MockSubnetsClientInterface {
    mock := &MockSubnetsClientInterface{ctrl: ctrl}
    mock.recorder = &MockSubnetsClientInterfaceMockRecorder{mock}
    return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubnetsClientInterface) EXPECT() *MockSubnetsClientInterfaceMockRecorder {
    return m.recorder
}

// Get mocks base method.
func (m *MockSubnetsClientInterface) Get(ctx context.Context, resourceGroupName, virtualNetworkName, subnetName string, options *aznetworkv2.SubnetsClientGetOptions) (aznetworkv2.SubnetsClientGetResponse, error) {
    m.ctrl.T.Helper()
    ret := m.ctrl.Call(m, "Get", ctx, resourceGroupName, virtualNetworkName, subnetName, options)
    ret0, _ := ret[0].(aznetworkv2.SubnetsClientGetResponse)
    ret1, _ := ret[1].(error)
    return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSubnetsClientInterfaceMockRecorder) Get(ctx, resourceGroupName, virtualNetworkName, subnetName, options interface{}) *gomock.Call {
    mr.mock.ctrl.T.Helper()
    return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSubnetsClientInterface)(nil).Get), ctx, resourceGroupName, virtualNetworkName, subnetName, options)
}

// BeginCreateOrUpdate mocks base method.
// func (m *MockSubnetsClientInterface) BeginCreateOrUpdate(ctx context.Context, resourceGroupName, virtualNetworkName, subnetName string, subnetParameters Subnet, options *SubnetsClientBeginCreateOrUpdateOptions) (*runtime.Poller[SubnetsClientCreateOrUpdateResponse], error) {
//     m.ctrl.T.Helper()
//     ret := m.ctrl.Call(m, "BeginCreateOrUpdate", ctx, resourceGroupName, virtualNetworkName, subnetName, subnetParameters, options)
//     ret0, _ := ret[0].(*runtime.Poller[SubnetsClientCreateOrUpdateResponse])
//     ret1, _ := ret[1].(error)
//     return ret0, ret1
// }

// // BeginCreateOrUpdate indicates an expected call of BeginCreateOrUpdate.
// func (mr *MockSubnetsClientInterfaceMockRecorder) BeginCreateOrUpdate(ctx, resourceGroupName, virtualNetworkName, subnetName, subnetParameters, options interface{}) *gomock.Call {
//     mr.mock.ctrl.T.Helper()
//     return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginCreateOrUpdate", reflect.TypeOf((*MockSubnetsClientInterface)(nil).BeginCreateOrUpdate), ctx, resourceGroupName, virtualNetworkName, subnetName, subnetParameters, options)
// }

// // BeginDelete mocks base method.
// func (m *MockSubnetsClientInterface) BeginDelete(ctx context.Context, resourceGroupName, virtualNetworkName, subnetName string, options *SubnetsClientBeginDeleteOptions) (*runtime.Poller[SubnetsClientDeleteResponse], error) {
//     m.ctrl.T.Helper()
//     ret := m.ctrl.Call(m, "BeginDelete", ctx, resourceGroupName, virtualNetworkName, subnetName, options)
//     ret0, _ := ret[0].(*runtime.Poller[SubnetsClientDeleteResponse])
//     ret1, _ := ret[1].(error)
//     return ret0, ret1
// }

// // BeginDelete indicates an expected call of BeginDelete.
// func (mr *MockSubnetsClientInterfaceMockRecorder) BeginDelete(ctx, resourceGroupName, virtualNetworkName, subnetName, options interface{}) *gomock.Call {
//     mr.mock.ctrl.T.Helper()
//     return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginDelete", reflect.TypeOf((*MockSubnetsClientInterface)(nil).BeginDelete), ctx, resourceGroupName, virtualNetworkName, subnetName, options)
// }